version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: systtechbot_postgres
    environment:
      POSTGRES_USER: systtechbot
      POSTGRES_PASSWORD: dev_password_change_in_production
      POSTGRES_DB: systtechbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U systtechbot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

