name: Build and Publish Docker Images

# Trigger: push в main, day06 и pull requests
on:
  push:
    branches:
      - main
      - day06
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.service }}
    runs-on: ubuntu-latest

    # Права для публикации в GitHub Container Registry
    permissions:
      contents: read
      packages: write

    # Matrix strategy: параллельная сборка 3 образов
    strategy:
      matrix:
        service: [bot, api, frontend]
      fail-fast: false  # Продолжить даже если один образ не собрался

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настройка Docker Buildx (для layer caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Вход в GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Генерация тегов для образа
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/systtechbot-${{ matrix.service }}
          tags: |
            # latest - только для main ветки
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # sha-{commit_sha} - для всех коммитов
            type=sha,prefix=sha-,format=short
            # pr-{number} - для Pull Requests
            type=ref,event=pr,prefix=pr-

      # 5. Сборка и публикация образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: devops/dockerfiles/${{ matrix.service }}.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Docker layer caching для ускорения повторных сборок
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/systtechbot-${{ matrix.service }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/systtechbot-${{ matrix.service }}:buildcache,mode=max

      # 6. Вывод информации о собранном образе
      - name: Image digest
        run: |
          echo "Successfully built and pushed ${{ matrix.service }} image"
          echo "Tags: ${{ steps.meta.outputs.tags }}"

